// AddItemControl.idl
import "BluePrintList.idl";
import "BluePrint.idl";
import "Result.idl";
import "BasketItem.idl";

namespace NutritionBasket
{
    runtimeclass AddItemControl : Windows.UI.Xaml.Controls.UserControl
    {
        AddItemControl();
        void OpenSearchDialog();
        void HideSearchResults();
        String SearchBarText();
        BluePrintList LocalSearchList{ get; };
        BluePrint SelectedItem{ get; };
        void SetSelectedItem(BluePrint item);
        void UpdateLocalBlueprints(BluePrint item);
        void UpdateSearchBarUX(Boolean state);
        void SearchBarText(String s);
    }
}