// AddItemControl.idl
import "BluePrintList.idl";
import "BluePrint.idl";
import "Result.idl";

namespace NutritionBasket
{
    runtimeclass AddItemControl : Windows.UI.Xaml.Controls.UserControl
    {
        AddItemControl();
        BluePrintList LocalSearchList{ get; };
        BluePrint SelectedItem{ get; };
        Windows.Foundation.Collections.IObservableVector<Result> USDAResults{ get; };
    }
}