// BasketItem.idl
import "BasketItemNutriElem.idl";

namespace NutritionBasket
{
    runtimeclass BasketItem : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        BasketItem(String name, String amount);
        String Name;
        String Amount;
        void AddElem(String name, String quantity);
        Windows.Foundation.Collections.IObservableVector<BasketItemNutriElem> Elems{ get; };
        UInt8 ItemIndex;
        UInt8 BasketIndex;
    }
}