// BasketItemNutriElem.idl
namespace NutritionBasket
{
	runtimeclass BasketItemNutriElem : Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		BasketItemNutriElem(String nutrient, String amount);
String Nutrient;
String Amount;
	}
}
