// BasketItem.idl
import "BluePrint.idl";

namespace NutritionBasket
{
    runtimeclass BasketItem : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        BasketItem();
        BluePrint BluePrint{ get; };
        void UpdateBluePrint(BluePrint print);
        UInt8 ItemIndex;
        UInt8 BasketIndex;
    }
}