//MainPage.idl
import "BodyViewModel.idl";

namespace NutritionBasket
{
	[bindable]
	runtimeclass MainPage : Windows.UI.Xaml.Controls.Page
	{
		MainPage();
		BodyViewModel BodyViewModel{ get; };
	}
}
