//MenuViewModel.idl
import "MenuItem.idl";

namespace NutritionBasket
{
    runtimeclass MenuViewModel
    {
        MenuViewModel();
        Windows.Foundation.Collections.IObservableVector<MenuItem> Options{ get; };
    }
}
