// NutriControl.idl
import "BluePrint.idl";

namespace NutritionBasket
{
    [default_interface]
    runtimeclass NutriControl : Windows.UI.Xaml.Controls.UserControl
    {
        NutriControl();
        static Windows.UI.Xaml.DependencyProperty BluePrintProperty{ get; };
        BluePrint BluePrint;
    }
}